name: Benjamin Ashmore
favicon: null
layout_spectrum: 0.5362140284851193
typography_spectrum: 0.29921283782459795
title: Learn about Benjamin Ashmore
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6064386158250272
  lightness: 0.3797975645866245
  saturation: 0.09478209330700338
  rhythmicContrast: 0.8808485963381827
purpose: []
